### ISSUE TITLE
TrueFantom.js doesn’t exists

### ISSUE THREAD

**Issue by ilikecereal1** [True-Fantom/TrueFantom#1]
The TrueFantom.js script doesn’t exist.

**OS**
Mobile Safari, iPadOS 16.3, iPad Pro 10.5-inch

**Comment by True-Fantom** [comment]
@ilikecereal1 

Yes. If you need an extension, use this link: https://true-fantom.github.io/true-fantom.js

But I would not recommend you to use extensions from this profile. They are not finished and may change at any time so that projects with older versions will not work. All these extensions will sooner or later move to the official repository, where they will definitely work stably. Better wait for this moment.

Ps: I made this site before the official one appeared, so now it doesn't make sense and is unlikely to work in the future.
